# Generated by Django 5.1.6 on 2025-02-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_category_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
